[project]
name = "matrix-forge"
version = "0.1.0"
description = "A basic tool to reproduce dot matrix fonts for use in my other projects"
readme = "README.md"
authors = [
    { name = "Lorenzo", email = "lorenzo@lrzodev.xyz" }
]
requires-python = ">=3.12"
dependencies = [
    "pyside6>=6.11.2",
]

[project.scripts]
matrix-forge = "matrix_forge.app:main"

[build-system]
requires = ["uv_build>=0.12.7,<0.13.0"]
build-backend = "uv_build"

[dependency-groups]
dev = [
    "pytest>=9.1.1",
]
